version: '3.8'
name: image-editor-api
services:
    api:
        container_name: image-editor-api
        image: image-editor-api:latest
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:80
        ports:
          - 80:80
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ImageEditor
      POSTGRES_USER: movian
      POSTGRES_PASSWORD: localpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: